services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/certs:/etc/nginx/certs
    env_file: .env.production
